# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterusagestate',
            name='current_usage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
