# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_waterusagestate_current_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterusagestate',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
