# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_waterusagestate_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterusagestate',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='waterusagestate',
            old_name='current_usage',
            new_name='usage',
        ),
        migrations.RemoveField(
            model_name='waterusagestate',
            name='check_date',
        ),
        migrations.AddField(
            model_name='waterusagestate',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 18, 33, 30, 970262, tzinfo=utc), verbose_name='date of check'),
        ),
        migrations.AlterField(
            model_name='waterusagestate',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
